### ISSUE TITLE
[NGM002] Constructor for mapping from {0} to {1} was not found

### ISSUE THREAD

**Issue by Genmutant** [DedAnton/NextGenMapper#112]
**Describe the bug**
I tried to map from a Dictionary<string,string> to a List<>, which used to work in 0.1.0-alpha.9
I now get the compilation error:

`  ConfigWithList.cs(22, 16): [NGM002] Constructor for mapping from {0} to {1} was not found, make sure that the {1} has a public constructor whose parameters correspond to the properties of the {0}`

**To Reproduce**
To reproduce run this example, which compiled before and now shows an compilation error:

```
using MapperTest;
using NextGenMapper;

namespace MapperTest {
    public class ConfigKeyValueEntry
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }

    public class ConfigWithDict
    {
        public Dictionary<string, string> Configurations { get; set; }
    }

    public class ConfigWithList
    {
        public List<ConfigKeyValueEntry> Configurations { get; set; }
        public static ConfigWithList FromRowDefinition(ConfigWithDict configWithDict)
        {
            return configWithDict.Map<ConfigWithList>();
        }
    }
}

// ReSharper disable once CheckNamespace
namespace NextGenMapper {
    internal static partial class Mapper
    {
        internal static List<ConfigKeyValueEntry> Map<To>(this Dictionary<string, string> source)
        {
            return source.Select(t => new ConfigKeyValueEntry {Key = t.Key, Value = t.Value}).ToList();
        }
    }
}
```

**Expected behavior**
That my custom mapping method is used, and it compiles without an error. Also that the error contains useful information, not uninterpolated placeholders.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: JetBrains Rider 2023.1 EAP 6
 - .NET SDK: 7.0.200
 - NextGenMapper:  0.1.0-alpha.10

**Comment by DedAnton** [comment]
@Genmutant, thank you for your feedback. The bug is fixed in the new version of the package (0.1.0-alpha.11) and is already released
